FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  FASTER_RCNN: true
  MASK_ON: true
  NUM_CLASSES: 81
  TYPE: mask_rcnn
MRCNN:
  BBOX2MASK:
    BBOX2MASK_ON: true
    INCLUDE_BBOX_PRED: true
    STOP_DET_W_GRAD: true
    TYPE: 2_layer
  CONV_INIT: MSRAFill
  DILATION: 1
  JOINT_FCN_MLP_HEAD: true
  RESOLUTION: 28
  ROI_MASK_HEAD: mask_rcnn_heads.ResNet_mask_rcnn_fcn_head_v1up4convs
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14
  ROI_XFORM_SAMPLING_RATIO: 2
NUM_GPUS: 8
OUTPUT_DIR: .
SOLVER:
  BASE_LR: 0.01
  GAMMA: 0.1
  LR_POLICY: steps_with_decay
  MAX_ITER: 180000
  STEPS:
  - 0
  - 120000
  - 160000
  WEIGHT_DECAY: 0.0001
TEST:
  DATASETS: ('coco_2014_minival', 'coco_split_voc_2014_minival', 'coco_split_nonvoc_2014_minival')
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_POST_NMS_TOP_N: 1000
  RPN_PRE_NMS_TOP_N: 1000
  SCALE: 800
TRAIN:
  BATCH_SIZE_PER_IM: 512
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  IMS_PER_BATCH: 1
  MAX_SIZE: 1333
  MRCNN_FILTER_LABELS: true
  MRCNN_LABELS_TO_KEEP: (1, 2, 3, 4, 5, 6, 7, 9, 15, 16, 17, 18, 19, 20, 40, 57, 58,
    59, 61, 63)
  RPN_PRE_NMS_TOP_N: 2000
  SCALES: (800,)
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl
USE_NCCL: false
